apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  ingressClassName: nginx
  rules:
    - host: GitX.com
      http:
        paths:
          - path: /posts/create
            pathType: ImplementationSpecific
            backend:
              serviceName: posts-clusterip-service
              servicePort: 4000
          - path: /posts
            pathType: ImplementationSpecific
            backend:
              serviceName: query-service
              servicePort: 4002
          - path: /posts/?(.*)/comments
            pathType: ImplementationSpecific
            backend:
              serviceName: comments-service
              servicePort: 4001
          - path: /?(.*)
            pathType: ImplementationSpecific
            backend:
              serviceName: client-service
              servicePort: 3000